#pragma once

int bnu_pwd_app_main(int argc, char **argv);
int bnu_ls_app_main(int argc, char **argv);
int bnu_lsblk_app_main(int argc, char **argv);
int bnu_mount_app_main(int argc, char **argv);
int bnu_unmount_app_main(int argc, char **argv);
int bnu_free_app_main(int argc, char **argv);
int bnu_top_app_main(int argc, char **argv);
int bnu_shutdown_app_main(int argc, char **argv);
int bnu_reboot_app_main(int argc, char **argv);
int bnu_date_app_main(int argc, char **argv);
int bnu_sleep_app_main(int argc, char **argv);
int bnu_mkdir_app_main(int argc, char **argv);
int bnu_touch_app_main(int argc, char **argv);
int bnu_rm_app_main(int argc, char **argv);
int bnu_cat_app_main(int argc, char **argv);
int bnu_head_app_main(int argc, char **argv);
int bnu_tail_app_main(int argc, char **argv);
int bnu_stty_app_main(int argc, char **argv);
int bnu_less_app_main(int argc, char **argv);
int bnu_wget_app_main(int argc, char **argv);
int bnu_curl_app_main(int argc, char **argv);
int bnu_base64_app_main(int argc, char **argv);
int bnu_md5sum_app_main(int argc, char **argv);
int bnu_sha256sum_app_main(int argc, char **argv);
int bnu_crc32_app_main(int argc, char **argv);
int bnu_grep_app_main(int argc, char **argv);
int bnu_wc_app_main(int argc, char **argv);
int bnu_xxd_app_main(int argc, char **argv);
int bnu_memorydump_app_main(int argc, char **argv);
const char *bnu__get_working_directory(void);
