[pytest]
testpaths = tests
addopts =
    -s
    -rP
    --embedded-services=idf,qemu
    --app-path=.
    --build-dir=build-qemu
    --qemu-cli-args="-nographic -machine esp32s3 -m 32M"
filterwarnings =
    ignore:record_xml_attribute is an experimental feature:pytest.PytestExperimentalApiWarning
