#pragma once

#include <stddef.h>
#include <stdint.h>

/*
 * Generated by src/modules/selftest/tool/gen_elf_loader_xip_fixture.py from
 * native_apps/examples/loader_selftest_esp32s3.elf -- do not hand-edit. See
 * that script's own doc comment to regenerate after changing
 * native_apps/examples/loader_selftest/main/main.c.
 */

extern const uint8_t elf_loader_xip_fixture[1820];
extern const size_t elf_loader_xip_fixture_len;
