#!/usr/bin/env python3
"""Regenerate elf_loader_xip_fixture.c/.h from the compiled fixture app.

elf_loader_test.c's elf_loader/xip and elf_loader/xip_streaming_fallback
selftest cases need a real, relocatable ELF -- not the hand-built,
manifest-only bytes fake_elf.c produces (see that file's own doc comment:
those are intentionally invalid past the manifest section, rejected before
relocation is ever attempted, so they can't exercise esp_elf_relocate_xip()
at all). native_apps/examples/loader_selftest/ is that real fixture app's
source; this script turns its compiled output into a plain C byte array
committed alongside the test, so the selftest doesn't need a cross-compile
step (or network access to the component registry -- see that app's
main/idf_component.yml) as part of every firmware build.

Usage, after editing native_apps/examples/loader_selftest/main/main.c:

    source $IDF_PATH/export.sh   # once per shell
    python3 native_apps/tools/build_apps.py --target elf --idf-target esp32s3 \\
        --app loader_selftest
    python3 src/modules/selftest/tool/gen_elf_loader_xip_fixture.py

Run from the repo root (or anywhere -- paths below are relative to this
script's own location, not the working directory).
"""

import pathlib
import sys

SCRIPT_DIR = pathlib.Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parents[3]
SOURCE_ELF = REPO_ROOT / "native_apps" / "examples" / "loader_selftest_esp32s3.elf"
OUT_C = SCRIPT_DIR.parent / "elf_loader_xip_fixture.c"
OUT_H = SCRIPT_DIR.parent / "elf_loader_xip_fixture.h"

HEADER_TEMPLATE = """\
#pragma once

#include <stddef.h>
#include <stdint.h>

/*
 * Generated by src/modules/selftest/tool/gen_elf_loader_xip_fixture.py from
 * native_apps/examples/loader_selftest_esp32s3.elf -- do not hand-edit. See
 * that script's own doc comment to regenerate after changing
 * native_apps/examples/loader_selftest/main/main.c.
 */

extern const uint8_t elf_loader_xip_fixture[{size}];
extern const size_t elf_loader_xip_fixture_len;
"""

SOURCE_TEMPLATE = """\
#include "elf_loader_xip_fixture.h"

/*
 * Generated by src/modules/selftest/tool/gen_elf_loader_xip_fixture.py from
 * native_apps/examples/loader_selftest_esp32s3.elf -- do not hand-edit. See
 * that script's own doc comment to regenerate after changing
 * native_apps/examples/loader_selftest/main/main.c.
 */

const uint8_t elf_loader_xip_fixture[{size}] = {{
{bytes_literal}
}};

const size_t elf_loader_xip_fixture_len = sizeof(elf_loader_xip_fixture);
"""


def format_bytes(data: bytes) -> str:
    lines = []
    for offset in range(0, len(data), 12):
        chunk = data[offset : offset + 12]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    return "\n".join(lines)


def main() -> int:
    if not SOURCE_ELF.is_file():
        print(f"error: {SOURCE_ELF} not found -- build it first, see this script's doc comment", file=sys.stderr)
        return 1

    data = SOURCE_ELF.read_bytes()
    OUT_H.write_text(HEADER_TEMPLATE.format(size=len(data)))
    OUT_C.write_text(SOURCE_TEMPLATE.format(size=len(data), bytes_literal=format_bytes(data)))
    print(f"Wrote {OUT_C} and {OUT_H} ({len(data)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
