#!/usr/bin/env python3
"""Generate deterministic gzip-compressed WebUI assets as a C header."""

import argparse
import gzip
import io
from pathlib import Path


ASSETS = ("index.html", "login.html", "index.css", "index.js")


def gzip_bytes(data: bytes) -> bytes:
    output = io.BytesIO()
    with gzip.GzipFile(filename="", mode="wb", fileobj=output, mtime=0) as archive:
        archive.write(data)
    return output.getvalue()


def format_array(name: str, data: bytes) -> list[str]:
    lines = [f"static const uint8_t {name}[] = {{"]
    for offset in range(0, len(data), 12):
        chunk = ", ".join(f"0x{byte:02x}" for byte in data[offset : offset + 12])
        lines.append(f"    {chunk},")
    lines.extend(
        (
            "};",
            f"static const size_t {name}_size = sizeof({name});",
            "",
        )
    )
    return lines


def generate(source_dir: Path) -> str:
    lines = [
        "/* Generated by tools/generate_webfiles.py. Do not edit. */",
        "#ifndef BRUCE_WEBUI_WEBFILES_H",
        "#define BRUCE_WEBUI_WEBFILES_H",
        "",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
    ]
    for filename in ASSETS:
        source = source_dir / filename
        if not source.is_file():
            raise FileNotFoundError(f"WebUI asset not found: {source}")
        identifier = "webui_" + filename.replace(".", "_") + "_gz"
        lines.extend(format_array(identifier, gzip_bytes(source.read_bytes())))
    lines.extend(("#endif /* BRUCE_WEBUI_WEBFILES_H */", ""))
    return "\n".join(lines)


def main() -> None:
    script_dir = Path(__file__).resolve().parent
    project_dir = script_dir.parent
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--source-dir",
        type=Path,
        default=project_dir / "embedded_resources" / "web_interface",
        help="directory containing index.html, login.html, index.css, and index.js",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=project_dir / "src" / "modules" / "webui" / "webfiles.h",
        help="generated C header path",
    )
    args = parser.parse_args()

    content = generate(args.source_dir.resolve())
    output = args.output.resolve()
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(content, encoding="ascii", newline="\n")


if __name__ == "__main__":
    main()
