#!/usr/bin/env python3
"""Generate module-local C headers embedding files from embedded_resources/.

To embed a new file: add one entry to RESOURCES below (source path under
embedded_resources/, the header it belongs in, and whether to store it
gzip-compressed) and drop the file in place. No other script or build-file
change is needed -- CMake discovers the header/source paths by querying this
script (--print-headers / --print-sources) at configure time.

Each entry produces a plain symbol, used directly (no macros):
  gzip entry "foo/bar.html" -> static const uint8_t foo_bar_html_gz[];
                                static const size_t foo_bar_html_gz_size;
  raw entry  "foo/bar.json" -> static const char foo_bar_json[];  (NUL-terminated)

Multiple entries may target the same header; each header only contains the
entries that name it, so e.g. core_sdk/ never has to see webui's or the
launcher's data -- each stays a private, module-local generated file, same
as a hand-written one would be.
"""

import argparse
import gzip
import io
import sys
from pathlib import Path

# (source path under embedded_resources/, header path relative to the repo
# root that the generated symbol belongs in, gzip-compress it?)
RESOURCES = [
    ("web_interface/index.html", "src/modules/webui/embedded_resources.h", True),
    ("web_interface/login.html", "src/modules/webui/embedded_resources.h", True),
    ("web_interface/index.css", "src/modules/webui/embedded_resources.h", True),
    ("web_interface/index.js", "src/modules/webui/embedded_resources.h", True),
    ("json/launcher.json", "src/modules/bruce_launcher/embedded_resources.h", False),
    ("json/extensions.json", "src/core/app_runner/embedded_resources.h", False),
]


def identifier(source: str) -> str:
    return "".join(character if character.isalnum() else "_" for character in source)


def gzip_bytes(data: bytes) -> bytes:
    output = io.BytesIO()
    with gzip.GzipFile(filename="", mode="wb", fileobj=output, mtime=0) as archive:
        archive.write(data)
    return output.getvalue()


def format_array(name: str, data: bytes, element_type: str = "uint8_t") -> list[str]:
    lines = [f"static const {element_type} {name}[] = {{"]
    for offset in range(0, len(data), 12):
        chunk = ", ".join(f"0x{byte:02x}" for byte in data[offset : offset + 12])
        lines.append(f"    {chunk},")
    lines.append("};")
    return lines


def generate_header(entries: list[tuple[str, str, bool]], resources_dir: Path) -> str:
    lines = [
        "/* Generated by tools/generate_embedded_resources.py. Do not edit.",
        " * To add or change an embedded resource, edit the RESOURCES list there. */",
        "#pragma once",
        "",
    ]
    # <stdint.h>/<stddef.h> are only needed for the uint8_t[]/size_t that a
    # gzip entry emits; a header with only plain `char[]` resources doesn't
    # use either, and an unused #include is worth avoiding since this file
    # is committed, not build-local.
    if any(gzip_it for _source, _header, gzip_it in entries):
        lines.extend(("#include <stddef.h>", "#include <stdint.h>", ""))
    for source, _header, gzip_it in entries:
        path = resources_dir / source
        if not path.is_file():
            raise FileNotFoundError(f"embedded resource not found: {path}")
        name = identifier(source)
        lines.append(f"/* {source}{' (gzip)' if gzip_it else ''} */")
        if gzip_it:
            gz_name = f"{name}_gz"
            data = gzip_bytes(path.read_bytes())
            lines.extend(format_array(gz_name, data))
            lines.append(f"static const size_t {gz_name}_size = sizeof({gz_name});")
        else:
            # NUL-terminated `char` (not uint8_t) so the array decays to a
            # plain `const char *` C string (strlen(), cJSON_Parse(), ...)
            # without a pointer-type mismatch at the assignment.
            data = path.read_bytes() + b"\x00"
            lines.extend(format_array(name, data, element_type="char"))
        lines.append("")
    return "\n".join(lines)


def headers_to_entries(resources: list[tuple[str, str, bool]]) -> dict[str, list[tuple[str, str, bool]]]:
    by_header: dict[str, list[tuple[str, str, bool]]] = {}
    for entry in resources:
        by_header.setdefault(entry[1], []).append(entry)
    return by_header


def write_if_changed(path: Path, content: str) -> None:
    # Skip the write when content is unchanged so the header's mtime doesn't
    # move and trigger a needless recompile of everything that includes it.
    if path.is_file() and path.read_text(encoding="ascii", errors="ignore") == content:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="ascii", newline="\n")


def main() -> None:
    script_dir = Path(__file__).resolve().parent
    project_dir = script_dir.parent
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument(
        "--resources-dir", type=Path, default=project_dir / "embedded_resources", help="directory holding source files"
    )
    parser.add_argument(
        "--project-dir", type=Path, default=project_dir, help="repo root that header/source paths are relative to"
    )
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument(
        "--print-headers", action="store_true", help="print each generated header's absolute path and exit"
    )
    mode.add_argument(
        "--print-sources", action="store_true", help="print the script plus every embedded source's absolute path and exit"
    )
    args = parser.parse_args()

    by_header = headers_to_entries(RESOURCES)

    if args.print_headers:
        for header in sorted(by_header):
            print((args.project_dir / header).resolve())
        return

    if args.print_sources:
        print(Path(__file__).resolve())
        for source, _header, _gzip in RESOURCES:
            print((args.resources_dir / source).resolve())
        return

    try:
        for header, entries in by_header.items():
            content = generate_header(entries, args.resources_dir.resolve())
            write_if_changed((args.project_dir / header).resolve(), content)
    except FileNotFoundError as error:
        print(f"generate_embedded_resources.py: {error}", file=sys.stderr)
        raise SystemExit(1) from error


if __name__ == "__main__":
    main()
