idf_component_register(SRCS
                    "main.c"
                    "core/apprunner/app_runner.c"
                    "core/config/config.c"
                    "core/storage/storage.c"
                    "core/wifi/wifi_common.c"
                    "core/wifi/wifi_webui.c"
                    "modules/launcher/launcher.c"
                    "modules/wifi/wifi_app.c"
                    REQUIRES
                    cjson
                    esp_event
                    driver
                    esp_driver_sdspi
                    esp_netif
                    esp_wifi
                    fatfs
                    log
                    lwip
                    spiffs
                    INCLUDE_DIRS
                    "."
                    "core/apprunner"
                    "core/config"
                    "core/storage"
                    "core/wifi"
                    "modules/launcher"
                    "modules/wifi")
