---
name: PR Check All envs on Dispatch

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: "Pull Request Number"
        type: string
        required: true

jobs:
  firmware:
    name: Build ${{ matrix.board }}
    runs-on: ubuntu-latest
    container: espressif/idf:v6.0.2
    strategy:
      fail-fast: false
      matrix:
        board:
          - "m5stack-cardputer"
          - "m5stack-cardputer-adv"
          - "m5stack-cplus2"
          - "m5stack-cplus1_1"
          - "m5stack-core"
          - "m5stack-core2"
          - "m5stack-cores3"
          - "m5stack-dinmeter"
          - "m5stack-sticks3"
          - "lilygo-t-embed-cc1101"
          - "lilygo-t-embed"
          - "lilygo-t-display-s3"
          - "lilygo-t-display-ttgo"
          - "xk404"
    steps:
      - uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ inputs.pr_number }}/merge
      - run: source "$IDF_PATH/export.sh" && python3 tools/board.py ${{ matrix.board }} build
      - uses: actions/upload-artifact@v4
        with:
          name: BruceIDF-${{ matrix.board }}
          path: build-board/${{ matrix.board }}/BruceIDF.bin
          retention-days: 5
          if-no-files-found: error
